/**
 *     NETWORK ACTION TYPES
 */

//Youtube API related actions
export const FETCH_VIDEOS_START = 'FETCH_VIDEOS_START'
export const FETCH_VIDEOS_SUCCESS = 'FETCH_VIDEOS_SUCCESS'
export const FETCH_VIDEOS_ERROR = 'FETCH_VIDEOS_ERROR'

