/**
 *     NETWORK ACTIONS
 */

//Youtube related actions
export const FETCH_ALL_CHANNELS_START = 'FETCH_ALL_CHANNELS_START'
export const FETCH_ALL_CHANNELS_SUCCESS = 'FETCH_ALL_CHANNELS_SUCCESS'
export const FETCH_ALL_CHANNELS_ERROR = 'FETCH_ALL_CHANNELS_ERROR'

export const FETCH_YOUTUBE_CHANNEL_INFO_START = 'FETCH_YOUTUBE_CHANNEL_INFO_START'
export const FETCH_YOUTUBE_CHANNEL_INFO_SUCCESS = 'FETCH_YOUTUBE_CHANNEL_INFO_SUCCESS'
export const FETCH_YOUTUBE_CHANNEL_INFO_ERROR = 'FETCH_YOUTUBE_CHANNEL_INFO_ERROR'

export const FETCH_CHANNEL_VIDEOS_START = 'FETCH_CHANNEL_VIDEOS_START'
export const FETCH_CHANNEL_VIDEOS_SUCCESS = 'FETCH_CHANNEL_VIDEOS_SUCCESS'
export const FETCH_CHANNEL_VIDEOS_ERROR = 'FETCH_CHANNEL_VIDEOS_ERROR'