/**
 *     NETWORK ACTION TYPES
 */

//Youtube API related actions
export const FETCH_CHANNEL_VIDEOS_START = 'FETCH_CHANNEL_VIDEOS_START'
export const FETCH_CHANNEL_VIDEOS_SUCCESS = 'FETCH_CHANNEL_VIDEOS_SUCCESS'
export const FETCH_CHANNEL_VIDEOS_ERROR = 'FETCH_CHANNEL_VIDEOS_ERROR'

/**
 *     LOCAL ACTIONS
 */
export const CHANNEL_IS_DESELECTED = 'CHANNEL_IS_DESELECTED'
export const CHANNEL_IS_RESELECTED = 'CHANNEL_IS_RESELECTED'
